
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author adnan
 */
public class Luggage extends javax.swing.JFrame {

    /**
     * Creates new form Luggage
     */
    public Luggage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Enter_No_of_Bags = new javax.swing.JLabel();
        Weight_of_Luggage = new javax.swing.JLabel();
        Input_Enter_No_of_Bags = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        Input_Weight_of_Luggage = new javax.swing.JTextField();
        Next = new javax.swing.JButton();
        Back = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(400, 320));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Luggage");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(150, 40, 120, 30);

        Enter_No_of_Bags.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Enter_No_of_Bags.setText("Enter No. of Bags");
        getContentPane().add(Enter_No_of_Bags);
        Enter_No_of_Bags.setBounds(44, 80, 131, 30);

        Weight_of_Luggage.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Weight_of_Luggage.setText("Weight of Luggage");
        getContentPane().add(Weight_of_Luggage);
        Weight_of_Luggage.setBounds(44, 128, 131, 30);

        Input_Enter_No_of_Bags.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        getContentPane().add(Input_Enter_No_of_Bags);
        Input_Enter_No_of_Bags.setBounds(234, 79, 110, 30);
        getContentPane().add(jLabel4);
        jLabel4.setBounds(175, 128, 0, 17);

        Input_Weight_of_Luggage.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        getContentPane().add(Input_Weight_of_Luggage);
        Input_Weight_of_Luggage.setBounds(234, 127, 110, 30);

        Next.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Next.setText("Next");
        Next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NextActionPerformed(evt);
            }
        });
        getContentPane().add(Next);
        Next.setBounds(234, 180, 90, 30);

        Back.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Back.setText("Back");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });
        getContentPane().add(Back);
        Back.setBounds(61, 180, 80, 30);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Man-at-airport.jpg.optimal.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 410, 300);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        Ticket tk = new Ticket();
        this.dispose();
        tk.show(); // TODO add your handling code here:
    }//GEN-LAST:event_BackActionPerformed

    private void NextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NextActionPerformed

        String enob = Input_Enter_No_of_Bags.getText();
        String ewol = Input_Weight_of_Luggage.getText();

        if (enob.isEmpty() || ewol.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please fill all mandatory fields");
        } else {
                  try {

                File file = new File("D:\\4th Semester\\Software Design and Architecture\\Muhammad Adnan Farooq Butt_023\\OnlineAeroplaneTicketBanking\\src\\userinfo.txt");

                // if file doesnt exists, then create it
                if (!file.exists()) {
                    file.createNewFile();
                }

                FileWriter fw = new FileWriter(file.getAbsoluteFile(), true);
                BufferedWriter bw = new BufferedWriter(fw);
               
                bw.write("Enter Number of Bags " + enob);    //step2: write it
                bw.write("\n");
                bw.write("Weight of Luggage " + ewol);
                bw.write("\n");
               
                bw.close();

                System.out.println("Done");
            
                this.dispose();
            } catch (IOException e) {
                e.printStackTrace();
            }
            Ticket_Bill tb = new Ticket_Bill();
            this.dispose();
            tb.show();
        }
    }//GEN-LAST:event_NextActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Luggage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Luggage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Luggage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Luggage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Luggage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JLabel Enter_No_of_Bags;
    private javax.swing.JTextField Input_Enter_No_of_Bags;
    private javax.swing.JTextField Input_Weight_of_Luggage;
    private javax.swing.JButton Next;
    private javax.swing.JLabel Weight_of_Luggage;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
