
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import javafx.scene.control.ButtonType;
import javax.net.ssl.SSLEngineResult;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author adnan
 */
public class Money_Transfer extends javax.swing.JFrame{

    /**
     * Creates new form Money_Transfer
     */
    public Money_Transfer() {
        initComponents();
    }
    
    public String getAccountNumber(){
        String accoutNumber = Input_Enter_Account_Number.getText();
        StringExtensions ext = new StringExtensions();
        return ext.safeTrim(accoutNumber);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Confirm_Transaction = new javax.swing.JButton();
        Enter_Account_Number = new javax.swing.JLabel();
        Account_Name = new javax.swing.JLabel();
        Account_Type = new javax.swing.JLabel();
        Amount = new javax.swing.JLabel();
        Input_Enter_Account_Number = new javax.swing.JTextField();
        Input_Amount = new javax.swing.JTextField();
        Input_Account_Name = new javax.swing.JTextField();
        Input_Account_Type = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(400, 323));
        setPreferredSize(new java.awt.Dimension(400, 323));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Money Transfer");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(114, 21, 160, 40);

        Confirm_Transaction.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Confirm_Transaction.setText("Confirm Transaction");
        Confirm_Transaction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Confirm_TransactionActionPerformed(evt);
            }
        });
        getContentPane().add(Confirm_Transaction);
        Confirm_Transaction.setBounds(120, 240, 180, 30);

        Enter_Account_Number.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Enter_Account_Number.setText("Enter Account Number");
        getContentPane().add(Enter_Account_Number);
        Enter_Account_Number.setBounds(45, 72, 159, 30);

        Account_Name.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Account_Name.setText("Account Name");
        getContentPane().add(Account_Name);
        Account_Name.setBounds(45, 111, 159, 30);

        Account_Type.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Account_Type.setText("Account Type");
        getContentPane().add(Account_Type);
        Account_Type.setBounds(45, 153, 159, 30);

        Amount.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Amount.setText("Amount");
        getContentPane().add(Amount);
        Amount.setBounds(45, 192, 159, 30);

        Input_Enter_Account_Number.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        getContentPane().add(Input_Enter_Account_Number);
        Input_Enter_Account_Number.setBounds(258, 71, 110, 30);

        Input_Amount.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        getContentPane().add(Input_Amount);
        Input_Amount.setBounds(258, 188, 110, 30);

        Input_Account_Name.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        getContentPane().add(Input_Account_Name);
        Input_Account_Name.setBounds(258, 110, 110, 30);

        Input_Account_Type.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Input_Account_Type.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Current", "Saving", "Money Market Deposit" }));
        getContentPane().add(Input_Account_Type);
        Input_Account_Type.setBounds(258, 149, 110, 30);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Malaysia_66.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 400, 300);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Confirm_TransactionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Confirm_TransactionActionPerformed
    
        String iean = getAccountNumber();
        String ian = Input_Account_Name.getText();
        String iat = (String) Input_Account_Type.getSelectedItem();
        String ia = Input_Amount.getText();

        if (iean.isEmpty() || ian.isEmpty() || iat.isEmpty() || ia.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please fill all mandatory fields");
        } else {
              try {

                File file = new File("D:\\4th Semester\\Software Design and Architecture\\Muhammad Adnan Farooq Butt_023\\OnlineAeroplaneTicketBanking\\src\\userinfo.txt");

                // if file doesnt exists, then create it
                if (!file.exists()) {
                    file.createNewFile();
                }

                FileWriter fw = new FileWriter(file.getAbsoluteFile(), true);
                BufferedWriter bw = new BufferedWriter(fw);
               
                bw.write(iean);    //step2: write it
                bw.write("\n");
                bw.write(ian);
                bw.write("\n");
                bw.write(iat);
                bw.write("\n");
                bw.write(ia);
                bw.write("\n");
                bw.close();
  System.out.println("Done");
                this.dispose();
            } catch (IOException e) {
                e.printStackTrace();
            }
              Main_Page mp = new Main_Page();
               JOptionPane.showMessageDialog(null, "Thank You For Travelling \n" + "Have A Safay Journey\n" +"From Qatar Airline");
       this.dispose();
       mp.show();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_Confirm_TransactionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Money_Transfer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Money_Transfer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Money_Transfer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Money_Transfer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Money_Transfer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Account_Name;
    private javax.swing.JLabel Account_Type;
    private javax.swing.JLabel Amount;
    private javax.swing.JButton Confirm_Transaction;
    private javax.swing.JLabel Enter_Account_Number;
    private javax.swing.JTextField Input_Account_Name;
    private javax.swing.JComboBox<String> Input_Account_Type;
    private javax.swing.JTextField Input_Amount;
    private javax.swing.JTextField Input_Enter_Account_Number;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
