
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author adnan
 */
public class Ticket_Bill extends javax.swing.JFrame {

    /**
     * Creates new form Ticket_Bill
     */
    public Ticket_Bill() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Submit = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        Name = new javax.swing.JLabel();
        Flight_Number = new javax.swing.JLabel();
        Seat_Number = new javax.swing.JLabel();
        Total_Bill = new javax.swing.JLabel();
        Input_Name = new javax.swing.JTextField();
        Input_Flight_Number = new javax.swing.JTextField();
        Input_Seat_Number = new javax.swing.JTextField();
        Input_Total_Bill = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(421, 300));
        setResizable(false);
        getContentPane().setLayout(null);

        Submit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Submit.setText("Submit");
        Submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitActionPerformed(evt);
            }
        });
        getContentPane().add(Submit);
        Submit.setBounds(170, 225, 100, 30);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Tikcet & Bill");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(144, 11, 130, 30);

        Name.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Name.setText("Name");
        getContentPane().add(Name);
        Name.setBounds(40, 50, 98, 30);

        Flight_Number.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Flight_Number.setText("Flight Number");
        getContentPane().add(Flight_Number);
        Flight_Number.setBounds(40, 90, 98, 30);

        Seat_Number.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Seat_Number.setText("Seat Number");
        getContentPane().add(Seat_Number);
        Seat_Number.setBounds(40, 130, 98, 30);

        Total_Bill.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Total_Bill.setText("Total Bill");
        getContentPane().add(Total_Bill);
        Total_Bill.setBounds(40, 170, 98, 30);

        Input_Name.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Input_Name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Input_NameActionPerformed(evt);
            }
        });
        getContentPane().add(Input_Name);
        Input_Name.setBounds(230, 90, 150, 30);

        Input_Flight_Number.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        getContentPane().add(Input_Flight_Number);
        Input_Flight_Number.setBounds(230, 50, 150, 30);

        Input_Seat_Number.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Input_Seat_Number.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Input_Seat_NumberActionPerformed(evt);
            }
        });
        getContentPane().add(Input_Seat_Number);
        Input_Seat_Number.setBounds(230, 130, 150, 30);

        Input_Total_Bill.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        getContentPane().add(Input_Total_Bill);
        Input_Total_Bill.setBounds(230, 170, 150, 30);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/sb10062851ai-001-e1516362885356.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 430, 300);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitActionPerformed

        String in = Input_Name.getText();
        String ifn = Input_Flight_Number.getText();
        String isn = Input_Seat_Number.getText();
        String itb = Input_Total_Bill.getText();

        if (in.isEmpty() || ifn.isEmpty() || isn.isEmpty() || itb.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please fill all mandatory fields");
        } else {
               try {

                File file = new File("D:\\4th Semester\\Software Design and Architecture\\Muhammad Adnan Farooq Butt_023\\OnlineAeroplaneTicketBanking\\src\\userinfo.txt");

                // if file doesnt exists, then create it
                if (!file.exists()) {
                    file.createNewFile();
                }

                FileWriter fw = new FileWriter(file.getAbsoluteFile(), true);
                BufferedWriter bw = new BufferedWriter(fw);
               
                bw.write(in);    //step2: write it
                bw.write("\n");
                bw.write(ifn);
                bw.write("\n");
                bw.write(isn);
                bw.write("\n");
                bw.write(itb);
                bw.write("\n");
                bw.close();
  System.out.println("Done");
                this.dispose();
            } catch (IOException e) {
                e.printStackTrace();
            }
            Money_Transfer mt = new Money_Transfer();
            this.dispose();
            mt.show();
        }

// TODO add your handling code here:
    }//GEN-LAST:event_SubmitActionPerformed

    private void Input_Seat_NumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Input_Seat_NumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Input_Seat_NumberActionPerformed

    private void Input_NameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Input_NameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Input_NameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ticket_Bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ticket_Bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ticket_Bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ticket_Bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ticket_Bill().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Flight_Number;
    private javax.swing.JTextField Input_Flight_Number;
    private javax.swing.JTextField Input_Name;
    private javax.swing.JTextField Input_Seat_Number;
    private javax.swing.JTextField Input_Total_Bill;
    private javax.swing.JLabel Name;
    private javax.swing.JLabel Seat_Number;
    private javax.swing.JButton Submit;
    private javax.swing.JLabel Total_Bill;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
