
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author adnan
 */
public class Ticket extends javax.swing.JFrame {

    /**
     * Creates new form Ticket
     */
    public Ticket() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Ticket_Type = new javax.swing.JLabel();
        Enter_No_of_Ticket = new javax.swing.JLabel();
        Flight_Ticket_Sreach = new javax.swing.JLabel();
        Input_Ticket_Type = new javax.swing.JComboBox<>();
        Input_Flight_Ticket_Sreach = new javax.swing.JComboBox<>();
        T_Next = new javax.swing.JButton();
        T_Back = new javax.swing.JButton();
        Input_Enter_No_of_Ticket = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(400, 300));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Ticket");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(155, 13, 90, 30);

        Ticket_Type.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Ticket_Type.setText("Ticket Type");
        Ticket_Type.setMaximumSize(new java.awt.Dimension(40, 17));
        Ticket_Type.setMinimumSize(new java.awt.Dimension(40, 17));
        Ticket_Type.setPreferredSize(new java.awt.Dimension(40, 17));
        getContentPane().add(Ticket_Type);
        Ticket_Type.setBounds(92, 62, 138, 30);

        Enter_No_of_Ticket.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Enter_No_of_Ticket.setText("Enter No. of Ticket");
        getContentPane().add(Enter_No_of_Ticket);
        Enter_No_of_Ticket.setBounds(92, 102, 138, 30);

        Flight_Ticket_Sreach.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Flight_Ticket_Sreach.setText("Flight Ticket Sreach ");
        getContentPane().add(Flight_Ticket_Sreach);
        Flight_Ticket_Sreach.setBounds(92, 141, 138, 30);

        Input_Ticket_Type.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Input_Ticket_Type.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "VIP", "Business", "Econmey" }));
        Input_Ticket_Type.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Input_Ticket_TypeActionPerformed(evt);
            }
        });
        getContentPane().add(Input_Ticket_Type);
        Input_Ticket_Type.setBounds(248, 61, 110, 30);

        Input_Flight_Ticket_Sreach.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Input_Flight_Ticket_Sreach.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "One Way", "Round Trip", "MutiCity" }));
        getContentPane().add(Input_Flight_Ticket_Sreach);
        Input_Flight_Ticket_Sreach.setBounds(248, 139, 110, 30);

        T_Next.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        T_Next.setText("Next");
        T_Next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                T_NextActionPerformed(evt);
            }
        });
        getContentPane().add(T_Next);
        T_Next.setBounds(260, 195, 100, 30);

        T_Back.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        T_Back.setText("Back");
        T_Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                T_BackActionPerformed(evt);
            }
        });
        getContentPane().add(T_Back);
        T_Back.setBounds(90, 195, 90, 30);

        Input_Enter_No_of_Ticket.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Input_Enter_No_of_Ticket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Input_Enter_No_of_TicketActionPerformed(evt);
            }
        });
        getContentPane().add(Input_Enter_No_of_Ticket);
        Input_Enter_No_of_Ticket.setBounds(248, 100, 110, 30);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/flight-ticket-booking-concept-computer-keyboard-flight-ticket-booking-concept-computer-keyboard-mouse-195447218.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        jLabel2.setToolTipText("");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 400, 300);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void T_BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_T_BackActionPerformed
        Arrival_Daparture ardp = new Arrival_Daparture();
        this.dispose();
        ardp.show();
    }//GEN-LAST:event_T_BackActionPerformed

    private void T_NextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_T_NextActionPerformed

        String ty = (String) Input_Ticket_Type.getSelectedItem();
        String enot = Input_Enter_No_of_Ticket.getText();
        String fts = (String) Input_Flight_Ticket_Sreach.getSelectedItem();
        
        if (ty.isEmpty() || enot.isEmpty() || fts.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please fill all mandatory fields");
        } else {
            try {

                File file = new File("D:\\4th Semester\\Software Design and Architecture\\Muhammad Adnan Farooq Butt_023\\OnlineAeroplaneTicketBanking\\src\\userinfo.txt");

                // if file doesnt exists, then create it
                if (!file.exists()) {
                    file.createNewFile();
                }

                FileWriter fw = new FileWriter(file.getAbsoluteFile(), true);
                BufferedWriter bw = new BufferedWriter(fw);
               
                bw.write(ty);    //step2: write it
                bw.write("\n");
                bw.write(enot);
                bw.write("\n");
                bw.write(fts);
                bw.write("\n");
                bw.close();
  System.out.println("Done");
                this.dispose();
            } catch (IOException e) {
                e.printStackTrace();
            }
            Luggage lg = new Luggage();
            this.dispose();
            lg.show();
        }

    }//GEN-LAST:event_T_NextActionPerformed

    private void Input_Enter_No_of_TicketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Input_Enter_No_of_TicketActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_Input_Enter_No_of_TicketActionPerformed

    private void Input_Ticket_TypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Input_Ticket_TypeActionPerformed
        // TODO add your handling code here:
        int tickettype = 0;
        int t=0;
        int VIP = 0;
        int Business = 0;
        int Econmey = 0;
        if(tickettype == VIP){
            t=80000;
        }
        else if(tickettype == Business){
            t=60000;
        }
        else if(tickettype == Econmey){
            t=40000;
        }
    }//GEN-LAST:event_Input_Ticket_TypeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ticket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ticket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ticket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ticket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ticket().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Enter_No_of_Ticket;
    private javax.swing.JLabel Flight_Ticket_Sreach;
    private javax.swing.JTextField Input_Enter_No_of_Ticket;
    private javax.swing.JComboBox<String> Input_Flight_Ticket_Sreach;
    private javax.swing.JComboBox<String> Input_Ticket_Type;
    private javax.swing.JButton T_Back;
    private javax.swing.JButton T_Next;
    private javax.swing.JLabel Ticket_Type;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
