
import static java.awt.image.ImageObserver.WIDTH;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Adnan Butt
 */
public class User_Information extends javax.swing.JFrame {

    public static String fname;

    public User_Information() {

        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox4 = new javax.swing.JComboBox<>();
        Input_Full_Name = new javax.swing.JTextField();
        CINC = new javax.swing.JLabel();
        Passport_Number = new javax.swing.JLabel();
        D_O_B = new javax.swing.JLabel();
        Full_Name = new javax.swing.JLabel();
        Date_of_Passport = new javax.swing.JLabel();
        Gender = new javax.swing.JLabel();
        Input_Gender = new javax.swing.JComboBox<>();
        Date = new javax.swing.JComboBox<>();
        Month = new javax.swing.JComboBox<>();
        Year = new javax.swing.JComboBox<>();
        PDate = new javax.swing.JComboBox<>();
        PMonth = new javax.swing.JComboBox<>();
        PYear = new javax.swing.JComboBox<>();
        Submit = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        Input_CINC = new javax.swing.JTextField();
        Input_Passport_Number = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(450, 400));
        setResizable(false);
        getContentPane().setLayout(null);

        Input_Full_Name.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Input_Full_Name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Input_Full_NameActionPerformed(evt);
            }
        });
        getContentPane().add(Input_Full_Name);
        Input_Full_Name.setBounds(189, 53, 230, 30);

        CINC.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        CINC.setText("CINC");
        getContentPane().add(CINC);
        CINC.setBounds(50, 90, 60, 30);

        Passport_Number.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Passport_Number.setText("Passport Number");
        getContentPane().add(Passport_Number);
        Passport_Number.setBounds(50, 210, 130, 30);

        D_O_B.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        D_O_B.setText("D.O.B");
        getContentPane().add(D_O_B);
        D_O_B.setBounds(50, 170, 50, 30);

        Full_Name.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Full_Name.setText("Full Name");
        getContentPane().add(Full_Name);
        Full_Name.setBounds(50, 54, 80, 30);

        Date_of_Passport.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Date_of_Passport.setText("Date of Passport");
        getContentPane().add(Date_of_Passport);
        Date_of_Passport.setBounds(50, 250, 130, 30);

        Gender.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Gender.setText("Gender");
        getContentPane().add(Gender);
        Gender.setBounds(50, 130, 60, 30);

        Input_Gender.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Input_Gender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female", "Others" }));
        Input_Gender.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(Input_Gender);
        Input_Gender.setBounds(190, 130, 230, 30);

        Date.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Date.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30" }));
        Date.setMinimumSize(new java.awt.Dimension(54, 21));
        getContentPane().add(Date);
        Date.setBounds(190, 170, 50, 30);

        Month.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Month.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "January", "February", "March", "April", "June", "July", "August", "September", "October", "Novmber", "December" }));
        getContentPane().add(Month);
        Month.setBounds(250, 170, 87, 30);

        Year.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Year.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1980", "1981", "1982", "1983", "1984", "1985", "1986", "1987", "1988", "1989", "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019", "2020", "2021" }));
        getContentPane().add(Year);
        Year.setBounds(350, 170, 70, 30);

        PDate.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        PDate.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30" }));
        PDate.setMinimumSize(new java.awt.Dimension(54, 21));
        getContentPane().add(PDate);
        PDate.setBounds(190, 250, 50, 30);

        PMonth.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        PMonth.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "January", "February", "March", "April", "June", "July", "August", "September", "October", "Novmber", "December" }));
        getContentPane().add(PMonth);
        PMonth.setBounds(250, 250, 90, 30);

        PYear.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        PYear.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1980", "1981", "1982", "1983", "1984", "1985", "1986", "1987", "1988", "1989", "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019", "2020", "2021" }));
        getContentPane().add(PYear);
        PYear.setBounds(350, 250, 70, 30);

        Submit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Submit.setText("Submit");
        Submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitActionPerformed(evt);
            }
        });
        getContentPane().add(Submit);
        Submit.setBounds(160, 310, 110, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("User Information");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(122, 12, 180, 30);
        getContentPane().add(Input_CINC);
        Input_CINC.setBounds(190, 90, 230, 30);
        getContentPane().add(Input_Passport_Number);
        Input_Passport_Number.setBounds(190, 210, 230, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/crop.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 450, 510);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Input_Full_NameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Input_Full_NameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Input_Full_NameActionPerformed

    private void SubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitActionPerformed

        String fname = Input_Full_Name.getText();
        String cnic = Input_CINC.getText();
        String gender = (String) Input_Gender.getSelectedItem();
        String dob = (String) Date.getSelectedItem() + " " + (String) Month.getSelectedItem() + " " + (String) Year.getSelectedItem();
        String pn = Input_Passport_Number.getText();
        String pdob = (String) PDate.getSelectedItem() + " " + (String) PMonth.getSelectedItem() + " " + (String) PYear.getSelectedItem();

        if (fname.isEmpty() || cnic.isEmpty() || gender.isEmpty()|| dob.isEmpty() || pn.isEmpty()|| pdob.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please fill all mandatory fields");
           
        } 
        else {
             try {

                File file = new File("D:\\4th Semester\\Software Design and Architecture\\Muhammad Adnan Farooq Butt_023\\OnlineAeroplaneTicketBanking\\src\\userinfo.txt");

                // if file doesnt exists, then create it
                if (!file.exists()) {
                    file.createNewFile();
                }

                FileWriter fw = new FileWriter(file.getAbsoluteFile(), true);
                BufferedWriter bw = new BufferedWriter(fw);
               
                bw.write(fname);    //step2: write it
                bw.write("\n");
                bw.write(cnic);
                bw.write("\n");
                bw.write(gender);
                bw.write("\n");
                bw.write(dob);
                bw.write("\n");
                bw.write(pn);
                bw.write("\n");
                bw.write(pdob);
                bw.write("\n");
                bw.close();

                System.out.println("Done");
            
                this.dispose();
            } catch (IOException e) {
                e.printStackTrace();
            }
            Arrival_Daparture ad = new Arrival_Daparture();
            this.dispose();
            ad.show();
        }
    }//GEN-LAST:event_SubmitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(User_Information.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(User_Information.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(User_Information.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(User_Information.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new User_Information().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CINC;
    private javax.swing.JLabel D_O_B;
    private javax.swing.JComboBox<String> Date;
    private javax.swing.JLabel Date_of_Passport;
    private javax.swing.JLabel Full_Name;
    private javax.swing.JLabel Gender;
    private javax.swing.JTextField Input_CINC;
    private javax.swing.JTextField Input_Full_Name;
    private javax.swing.JComboBox<String> Input_Gender;
    private javax.swing.JTextField Input_Passport_Number;
    private javax.swing.JComboBox<String> Month;
    private javax.swing.JComboBox<String> PDate;
    private javax.swing.JComboBox<String> PMonth;
    private javax.swing.JComboBox<String> PYear;
    private javax.swing.JLabel Passport_Number;
    private javax.swing.JButton Submit;
    private javax.swing.JComboBox<String> Year;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel7;
    // End of variables declaration//GEN-END:variables

    String getName(String fname) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
